{
  "formatVersion": "1.1",
  "component": {
    "group": "org.abstruck.zysdk",
    "module": "zysdk",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "zysdk-0.1.2.jar",
          "url": "zysdk-0.1.2.jar",
          "size": 72146,
          "sha512": "d2d2c70423f165e801e035704d3079b756899f3bfe74bf18371fca25ef3cc93c3d11482d486d08325a99d2c4026482df5bb5709deb7a5a537f14d28e2c5c2a5e",
          "sha256": "d8aec66d0f3c7b529c0599c686195e50da7e284da52ace9603903a80851a28ae",
          "sha1": "429a350ab11718d68ed6a87d146fd4f5dcd8b8bb",
          "md5": "93a0babc3492e1943aa5eade2ecc6b04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "zysdk-0.1.2.jar",
          "url": "zysdk-0.1.2.jar",
          "size": 72146,
          "sha512": "d2d2c70423f165e801e035704d3079b756899f3bfe74bf18371fca25ef3cc93c3d11482d486d08325a99d2c4026482df5bb5709deb7a5a537f14d28e2c5c2a5e",
          "sha256": "d8aec66d0f3c7b529c0599c686195e50da7e284da52ace9603903a80851a28ae",
          "sha1": "429a350ab11718d68ed6a87d146fd4f5dcd8b8bb",
          "md5": "93a0babc3492e1943aa5eade2ecc6b04"
        }
      ]
    }
  ]
}
